# Stack configuration file:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-14.3
extra-deps:
  - git: https://github.com/IagoAbal/haskell-z3
    commit: e79d2497b45f37365ca7d5b060c72f8624f2d7e2
extra-include-dirs:
  - /usr/include/z3/
